name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          hheroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jkpokemon"
          heroku_email: "juha.koivu@outlook.com"
          healthcheck: "https://jkpokemon.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true